brainstorm/urls.py
from django.urls import path
from . import views


app_name = 'brainstorm'


urlpatterns = [
    path('', views.BrainstormHome.as_view(), name='home'),
    path('questions/', views.BSCreateView.as_view(), name='questions'),  # todo add View
    path('result/', views.BSListView, name='result'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.BSUpdateView.as_view(), name='update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.BSDeleteView.as_view(), name='delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
]

davis_t_shirt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('brainstorm/', include('brainstorm.urls')),
]

brainstorm/models.py
from django.db import models
from datetime import datetime


class Brainstorms(models.Model):
    class Meta:
        db_table = "brainstorms"
        verbose_name = "アイデア"
        verbose_name_plural = "アイデア"

    date = models.DateField(verbose_name="日付", default=datetime.now)
    title = models.CharField(verbose_name="タイトル", max_length=50)
    answer1 = models.TextField(verbose_name="そのサービスはどのような課題を解決するの？", null=True, blank=True)
    answer2 = models.TextField(verbose_name="もし新聞に取り上げられたらどんな記事になる？", null=True, blank=True)
    answer3 = models.TextField(verbose_name="ほかの商品・サービスに例えると？", null=True, blank=True)
    answer4 = models.TextField(verbose_name="一言でそのサービスを紹介すると？", null=True, blank=True)
    answer5 = models.TextField(verbose_name="友人に勧めるならどう勧める？", null=True, blank=True)
    answer6 = models.TextField(verbose_name="競合するサービスに対する優位性は？", null=True, blank=True)
    answer7 = models.TextField(verbose_name="回答", null=True, blank=True)
    answer8 = models.TextField(verbose_name="回答", null=True, blank=True)
    answer9 = models.TextField(verbose_name="回答", null=True, blank=True)
    answer10 = models.TextField(verbose_name="回答", null=True, blank=True)
    answer11 = models.TextField(verbose_name="回答", null=True, blank=True)
    answer12 = models.TextField(verbose_name="回答", null=True, blank=True)
    answer13 = models.TextField(verbose_name="回答", null=True, blank=True)

    def __str__(self):
        return self.title

brainstorm/forms.py
from django import forms
from .models import Brainstorms


class BSForm(forms.ModelForm):
    """
   新規データ登録画面用のフォーム定義
   """

    class Meta:
        model = Brainstorms
        fields = ['date', 'title', 'answer1', 'answer2', 'answer3', 'answer4', 'answer5', 'answer6', 'answer7',
                  'answer8', 'answer9', 'answer10', 'answer11', 'answer12', 'answer13']

brainstorm/views.py
from django.shortcuts import render
from .models import Brainstorms
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from .forms import BSForm
from django.urls import reverse_lazy


class BrainstormHome(TemplateView):
    template_name = 'brainstorm/brainstorm_home.html'


class BSListView(ListView):
    model = Brainstorms
    template_name = 'brainstorm/list.html'

    # アイデアテーブルの全データを取得するメソッドを定義/object_listと言う名前でオブジェクトが渡される
    def queryset(self):
        return Brainstorms.objects.all()


class BSCreateView(CreateView):
    model = Brainstorms
    form_class = BSForm
    success_url = reverse_lazy('brainstorm:create_done')


def create_done(request):
    return render(request, 'brainstorm/create_done.html')


class BSUpdateView(UpdateView):
    model = Brainstorms
    form_class = BSForm
    success_url = reverse_lazy('brainstorm:update_done')


def update_done(request):
    return render(request, 'brainstorm/update_done.html')


class BSDeleteView(DeleteView):
    # 利用するモデルを指定
    model = Brainstorms
    # 削除処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('brainstorm:delete_done')


def delete_done(request):
    return render(request, 'brainstorm/delete_done.html')

templates/brainstorm/base.html
<!doctype html>
<html lang="ja">
<head>
 <meta charset="utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {# Bootstrap4を使う #}
 <!-- linkタグでbootstrapのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
 <!-- linkタグでDataTableのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>

 <!-- DataTablesのjavascrit読み込み-->
 <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
 <!-- タイトルの設定-->
 <title>ブレインストーミングアプリ</title>
</head>
<body>
 {% block content %}
  <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->
 {% endblock %}
 <!-- bootstrapのjavascrit読み込み-->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
<!-- Databableの定義-->
 <script>
    jQuery(function($){
      // デフォルトの設定を変更
      $.extend( $.fn.dataTable.defaults, {
          language: {
              url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
              }
              });
      $("#ideas_list").DataTable({
          "searching": true,     //検索機能
          "paging":   true,      //ページング機能
          "ordering": true,      //ソート機能
          "lengthChange": true,  //件数切り替え機能

          }).columns.adjust().draw();
          });
 </script>
</body>
</html>

templates/brainstorm/brainstorm_home.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>ブレインストームアプリ</title>
  </head>
  <body>
    <a href="{% url 'brainstorm:questions' %}">新規</a>
    <a href="{% url 'brainstorm:result' %}">編集</a>
  </body>
</html>

templates/brainstorm/brainstorms_form.html
<!-- 親テンプレートを読み込む-->
{% extends 'brainstorm/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'brainstorm:result' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">一覧表示</li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
         <h3><b>ブレインストーミングアプリ</b></h3></div>
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <div class="table-responsive">
         <table id=ideas_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">日付</th>
                 <th class="text-center">サービス名</th>
                 <th class="text-center">問いかけ</th>
                 <th class="text-center">回答</th>
                 <th class="text-center">更新・削除</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100">{{ item.date}}</td>
                   <td class="text-center" width="100">{{ item.title }}</td>
                   <td class="text-center" width="140">{{ item.question }}</td>
                   <td class="text-center" width="140">{{ item.answer }}</td>
                   <td class="text-center" width="140">
                       <a class="btn btn-primary" href="{% url 'brainstorm:ideas_update' item.pk %}">更新ページ</a>
                       <a class="btn btn-danger" href="{%  url 'brainstorm:ideas_delete' item.pk %}">削除ページ</a>
                   </td>
                 </tr>
             {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
       </div>
      </div>
      </div>
   </div>
  </div>
{% endblock content %}

templates/brainstorm/create_done.html
{% extends 'brainstorm/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">ブレインストーミングアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>ブレインストーミングアプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ登録が正常終了しました。</div>
{% endblock content %}

templates/brainstorm/delete_done.html
{% extends 'brainstorm/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'brainstorm:list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">ブレインストーミングアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>ブレインストーミングアプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ削除処理が正常終了しました。</div>
{% endblock content %}

templates/brainstorm/list.html
<!-- 親テンプレートを読み込む-->
{% extends 'brainstorm/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'brainstorm:ideas_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">一覧表示</li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
         <h3><b>ブレインストーミングアプリ</b></h3></div>
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <div class="table-responsive">
         <table id=ideas_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">日付</th>
                 <th class="text-center">サービス名</th>
                 <th class="text-center">問いかけ</th>
                 <th class="text-center">回答</th>
                 <th class="text-center">更新・削除</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100">{{ item.date}}</td>
                   <td class="text-center" width="100">{{ item.title }}</td>
                   <td class="text-center" width="140">{{ item.question }}</td>
                   <td class="text-center" width="140">{{ item.answer }}</td>
                   <td class="text-center" width="140">
                       <a class="btn btn-primary" href="{% url 'brainstorm:update' item.pk %}">更新ページ</a>
                       <a class="btn btn-danger" href="{%  url 'brainstorm:delete' item.pk %}">削除ページ</a>
                   </td>
                 </tr>
             {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
       </div>
      </div>
      </div>
   </div>
  </div>
{% endblock content %}

templates/brainstorm/update_done.html
{% extends 'brainstorm/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'brainstorm:list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">ブレインストーミングアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>ブレインストーミングアプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ更新処理が正常終了しました。</div>
{% endblock content %}